# Original data
data = [
    "Google Search",
    "google.com",
    "YouTube",
    "youtube.com",
    "Facebook",
    "facebook.com",
    "Twitter",
    "twitter.com",
    "Instagram",
    "instagram.com",
    "Baidu",
    "baidu.com",
    "Wikipedia",
    "wikipedia.org",
    "Yandex",
    "yandex.ru",
    "Yahoo",
    "yahoo.com",
    "xVideos",
    "xvideos.com",
    "WhatsApp",
    "whatsapp.com",
    "Pornhub",
    "pornhub.com",
    "Xnxx",
    "xnxx.com",
    "Amazon",
    "amazon.com",
    "Yahoo JP",
    "yahoo.co.jp",
    "Live",
    "live.com",
    "Netflix",
    "netflix.com",
    "Reddit",
    "reddit.com",
    "TikTok",
    "tiktok.com",
    "Docomo",
    "docomo.ne.jp",
    "LinkedIn",
    "linkedin.com",
    "Office",
    "office.com",
    "Samsung",
    "samsung.com",
    "Yandex Turbo Pages",
    "turbopages.org",
    "VK",
    "vk.com",
    "xHamster",
    "xhamster.com",
    "Weather",
    "weather.com",
    "Twitch",
    "twitch.tv",
    "Mail.Ru",
    "mail.ru",
    "Naver",
    "naver.com",
    "Discord",
    "discord.com",
    "Bing",
    "bing.com",
    "Roblox",
    "roblox.com",
    "Bilibili",
    "bilibili.com",
    "Microsoft Online",
    "microsoftonline.com",
    "Pinterest",
    "pinterest.com",
    "Zoom",
    "zoom.us",
    "QQ",
    "qq.com",
    "DuckDuckGo",
    "duckduckgo.com",
    "Microsoft",
    "microsoft.com",
    "Fandom",
    "fandom.com",
    "Quora",
    "quora.com",
    "Yahoo! News",
    "news.yahoo.com",
    "eBay",
    "ebay.com",
    "MSN",
    "msn.com",
    "Globo",
    "globo.com",
    "Stripchat",
    "stripchat.com",
    "Booking",
    "booking.com",
    "OK.ru",
    "ok.ru"]

# Check the length of data
if len(data) % 2 != 0:
    print(len(data))
    print("Error: Incomplete data - Each website name should be followed by its URL.")
else:
    websites = []
    for i in range(0, len(data), 2):
        website = {
            "name": data[i],
            "url": data[i + 1].lower()
        }
        websites.append(website)

    for website in websites:
        print(website['name'])
