# Generated by Django 5.0.6 on 2024-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
