# Generated by Django 5.0.6 on 2024-05-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_webpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.keyword')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.webpage')),
            ],
            options={
                'unique_together': {('webpage', 'keyword')},
            },
        ),
    ]
