# Generated by Django 5.0.6 on 2024-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_keywordmapping_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
